# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 11:44
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db.models import BooleanField, TextField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabotapp', '0006_auto_20170821_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='NimWakuStatusCheck',
            fields=[
                ('log_level',       TextField(help_text=b'Canary tool logging level.',  default='ERROR')),
                ('address',         TextField(help_text=b'Waku node multiaddress.',     null=True)),
                ('proto_relay',     BooleanField(help_text=b'Relay Protocol Check',     default=True)),
                ('proto_store',     BooleanField(help_text=b'Store Protocol Check',     default=False)),
                ('proto_filter',    BooleanField(help_text=b'Filter Protocol Check',    default=False)),
                ('proto_lightpush', BooleanField(help_text=b'Lightpush Protocol Check', default=False)),
                ('wss_cert',        TextField(help_text=b'Cert for connecting to WSS port.', null=True)),
                ('wss_key',         TextField(help_text=b'Cert key for connecting to WSS port.', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cabotapp.statuscheck',),
        ),
    ]
